//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Blog
    {
        public int BlogId { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd HH:mm:ss}")]
        public Nullable<System.DateTime> CurrentTime { get; set; }
        public string Title1 { get; set; }
        public string Script1 { get; set; }
        public byte[] Img1 { get; set; }
        public string Title2 { get; set; }
        public string Script2 { get; set; }
        public byte[] Img2 { get; set; }
        public string Title3 { get; set; }
        public string Script3 { get; set; }
        public byte[] Img3 { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string Name { get; set; }
        public string Title4 { get; set; }
        public string Script4 { get; set; }
        public byte[] Img4 { get; set; }
        public Nullable<int> CampId { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Campaign Campaign { get; set; }
    }
}
