//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Campaigns = new HashSet<Campaign>();
        }

        public int CategoryId { get; set; }
        [Required(ErrorMessage = "Please enter Name.")]
        [RegularExpression("^[a-zA-Z\\s]{1,50}$", ErrorMessage = "Name is invalid.")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter Title.")]
        [MaxLength(100, ErrorMessage = "Maximum 100 characters.")]
        public string Title1 { get; set; }
        [Required(ErrorMessage = "Please enter Script.")]
        [MaxLength(1000, ErrorMessage = "Maximum 1000 characters.")]
        public string Script1 { get; set; }
        public byte[] Img1 { get; set; }
        [Required(ErrorMessage = "Please enter Title.")]
        [MaxLength(100, ErrorMessage = "Maximum 100 characters.")]
        public string Title2 { get; set; }
        [Required(ErrorMessage = "Please enter Script.")]
        [MaxLength(1000, ErrorMessage = "Maximum 1000 characters.")]
        public string Script2 { get; set; }
        [Required(ErrorMessage = "Please enter Title.")]
        [MaxLength(100, ErrorMessage = "Maximum 100 characters.")]
        public string Title3 { get; set; }
        [Required(ErrorMessage = "Please enter Script.")]
        [MaxLength(1000, ErrorMessage = "Maximum 1000 characters.")]
        public string Script3 { get; set; }
        public Nullable<int> Status { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campaign> Campaigns { get; set; }
    }
}
