//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ngoEntities : DbContext
    {
        public ngoEntities()
            : base("name=ngoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<Business> Businesses { get; set; }
        public virtual DbSet<Campaign> Campaigns { get; set; }
        public virtual DbSet<Campaign_Detail> Campaign_Detail { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Donor> Donors { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Fund> Funds { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<REF_CAMP_PARTNER> REF_CAMP_PARTNER { get; set; }
        public virtual DbSet<REF_EMP_ROLE> REF_EMP_ROLE { get; set; }
        public virtual DbSet<REF_FUND_CAMP_DONOR> REF_FUND_CAMP_DONOR { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
    }
}
