//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int MemberId { get; set; }
        public string Biography { get; set; }
        public Nullable<int> BusinessId { get; set; }
        public Nullable<int> Status { get; set; }
        public string FullName { get; set; }
        public byte[] Img { get; set; }
    
        public virtual Business Business { get; set; }
    }
}
