//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partner()
        {
            this.REF_CAMP_PARTNER = new HashSet<REF_CAMP_PARTNER>();
        }

        public int PartnerId { get; set; }
        [Required(ErrorMessage = "Please enter Full Name.")]
        [RegularExpression("^[a-zA-Z\\s]{1,50}$", ErrorMessage = "Name is invalid.")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter Email.")]
        [MaxLength(50, ErrorMessage = "Maximum 50 characters.")]
        [RegularExpression("^[\\w.]{5,32}[@][\\w.]{2,9}[.][a-zA-Z]{2,9}$", ErrorMessage = "Email is invalid.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter Phone.")]
        [RegularExpression("^[0][0-9]{9}$", ErrorMessage = "Phone is invalid. (0987654321 or 0123456789...)")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Please enter Address.")]
        [MaxLength(255, ErrorMessage = "Maximum 255 characters.")]
        public string Address { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> Status { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REF_CAMP_PARTNER> REF_CAMP_PARTNER { get; set; }
    }
}
