//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class REF_FUND_CAMP_DONOR
    {
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd HH:mm:ss}")]
        public Nullable<System.DateTime> CurrentTime { get; set; }
        public string Description { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> CampId { get; set; }
        public Nullable<int> FundId { get; set; }
        public int DonateId { get; set; }
        public Nullable<int> DonorId { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual Donor Donor { get; set; }
        public virtual Fund Fund { get; set; }
    }
}
